language: node_js
node_js: "6"
before_install:
  - sudo apt-get -qq update && sudo apt-get install -y curl
  - rvm use 2.3.1 --install --binary --fuzzy
  - npm install jspm
  - ./node_modules/.bin/jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
install:
  - npm install
  - bundle install --path vendor
script:
  - gulp lint
  - gulp test
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && ([ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_BRANCH" == "dev" ]); then gulp release; fi
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  bundler: true
  directories:
    - cache
    - node_modules
    - jspm_packages
env:
  global:
    - AWS_KEY=AKIAI6YF75KDZNQJBFXA
    - secure: dsQliAKcpbWRnMbYXR6GwT63aPHzNew7M1MvvdvnsWKjSxSls4h+c/HXzbcLTBJFWqL798bcvCN+GEmQRuJaq+dJxsDFu/rcGVws1KlSNtIV/snIy1cNdQJHD13NkDh0lG33tfHz+eL2rwudDI9NqMKXFi5HbL5ehTQbnLLwxRbkMovD1QN+rfhlv/BywvRHHX+qjcScqch3nYd0LDp4DeetEINweuC/4UEcV4X2uKso5HOq/R4vPD8CI5YVSZNmc187k0OAnXA/trG0TrvUwbzPUW7osjNdD+scnCD9zYbzKETU3LqcJij72Ai7j93fHsbq8Wj08tr6R0h7vwt7SabZ7mmUtFxlwniLBElF2UrZPamSsM1dgU+sGV9lxhtOBFRpXoN0GjJ4WeIJpfOQCDOqG9/d9DzY0gAFILqGO58wDRi2L8FxKF9Q8G/jRg7S1alkZAswjFRH9RgZFc8/TiL/maceggcAurckJkYwyEbsQRrPqqsnTNkZmE9+H8oMK5IJ+Fatj+/32lKT/ZEyJfxYii6yzgVOHRo4W7uqB4U1l0f/ddYLb4YbcGwP+kef6DvH37tjMFto2jepy/V1JCHDscw7DVFc9IL4QWBtPjL1kyLLEkQ4IG+nX1vs4bMaI1SRGwz/xUxmJIC3X5dxFlj6NT3nUow3O9seoPRMbeI=
    - secure: qOF4BXNkfWCOSqZ1X+HfeToxV2YxsAeFgdJD+aY39UU6LMG800XJIRlIFbDl6MDauFsYo3DMzxIxClqN5VNSV0/5x0Yrx0oMMEMl1WHO1AIJE0u3M18v70wROUW6O7Z4+eSkh9cAVAqpo2saAmaC7Vi2Jz1UlWbhTTd2CIKWSyKZgn6ZlzE8WC55gRtwwH4NlJixDSrwe/uReRdfvoH/WhWjpLxd1WeZGGpn2LuciciKc3Y0cc//vmz2E216OXmNW2veA8AU12BMPHi1PSaA10F8NxYnljmPOU2wAQDb4wHej0Hd9cQjz53365PJ8PpJNbZepYSjufEasdnW3fzO1TRbXi8TafuMcEKbs6k6ocVMyk8XMs0ZbLOavKnh+6Vhf++KAlWKKhXCdl2GQ2f/1B0uRHAH08ph4jREBK3AdBepZK/CeXL7Ti7+u9vFFC++sHtz1qFQpjv+k5Ip15KtbMDqfDASMDJdH2h3o/dLHpz9+tCE3fFMuRet/aRnsjJkULful83ywDlfDfX+79G/JJZum6gA/OCCFm8s8l+SEKz8zqMyYcYgEHyBad062GjYpZ6vWVv4gAgpQKLcICVsyoWt2OWNRv7AUn19bQgI1bxL/lFGjRlWBXrF0zQc4axC0VqoaHaq/Hcy7DnT7Ww9vjeBnLWEyu0DOFftpXNdC2Y=
deploy:
  - provider: s3
    access_key_id: $AWS_KEY
    secret_access_key: $AWS_SECRET
    bucket: cru-givedev
    acl: public_read
    cache_control: "max-age=300"
    local-dir: dist
    skip_cleanup: true
    on:
      branch: dev

  - provider: s3
    access_key_id: $AWS_KEY
    secret_access_key: $AWS_SECRET
    bucket: cru-givestage
    acl: public_read
    cache_control: "max-age=3600"
    local-dir: dist
    skip_cleanup: true
after_deploy:
  - chmod +x ./.travis/invalidate_cloudfront_cache.sh
  - ./.travis/invalidate_cloudfront_cache.sh $AWS_KEY $AWS_SECRET
after_script:
  - bundle exec rake
