language: node_js
node_js: node
before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
install:
- npm install
script:
- gulp lint
- gulp test
- gulp release
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: dsQliAKcpbWRnMbYXR6GwT63aPHzNew7M1MvvdvnsWKjSxSls4h+c/HXzbcLTBJFWqL798bcvCN+GEmQRuJaq+dJxsDFu/rcGVws1KlSNtIV/snIy1cNdQJHD13NkDh0lG33tfHz+eL2rwudDI9NqMKXFi5HbL5ehTQbnLLwxRbkMovD1QN+rfhlv/BywvRHHX+qjcScqch3nYd0LDp4DeetEINweuC/4UEcV4X2uKso5HOq/R4vPD8CI5YVSZNmc187k0OAnXA/trG0TrvUwbzPUW7osjNdD+scnCD9zYbzKETU3LqcJij72Ai7j93fHsbq8Wj08tr6R0h7vwt7SabZ7mmUtFxlwniLBElF2UrZPamSsM1dgU+sGV9lxhtOBFRpXoN0GjJ4WeIJpfOQCDOqG9/d9DzY0gAFILqGO58wDRi2L8FxKF9Q8G/jRg7S1alkZAswjFRH9RgZFc8/TiL/maceggcAurckJkYwyEbsQRrPqqsnTNkZmE9+H8oMK5IJ+Fatj+/32lKT/ZEyJfxYii6yzgVOHRo4W7uqB4U1l0f/ddYLb4YbcGwP+kef6DvH37tjMFto2jepy/V1JCHDscw7DVFc9IL4QWBtPjL1kyLLEkQ4IG+nX1vs4bMaI1SRGwz/xUxmJIC3X5dxFlj6NT3nUow3O9seoPRMbeI=
