name: Build

on:
  push: 
    branches: [staging, master]
  pull_request:
    branches: [staging, master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 8
      
      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache
      
      - name: Lint Check
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Help Codecov detect commit SHA
          fetch-depth: 2
      
      - uses: actions/setup-node@v2
        with:
          node-version: 8
      
      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache
      
      - name: Run Tests
        run: yarn test
      
      - name: Upload Codecov Reports
        uses: codecov/codecov-action@v2 
   
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test, codecov]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 8
      
      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache
      
      - name: Build App
        run: yarn run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
      - name: Deploy to S3 | Staging
        if: github.ref == 'refs/heads/staging'
        run: aws s3 sync dist s3://cru-givestage --region us-east-1 --acl public-read --cache-control 'public, max-age=300' --delete
      
      - name: First Deploy to S3 | Production
        if: github.ref == 'refs/heads/master'
        run: aws s3 sync dist s3://cru-giveprod --region us-east-1 --acl public-read --cache-control 'public, max-age=300'
      
      - name: Second Deploy to S3 | Production
        if: github.ref == 'refs/heads/master'
        run: aws s3 sync dist s3://cru-giveprod --region us-east-1 --acl public-read --cache-control 'public, max-age=300' --delete
      
      - name: AWS Cloudfront | Staging
        if: github.ref == 'refs/heads/staging'
        run: aws cloudfront create-invalidation --distribution-id EPXENORNKOQM --paths "/*"
      
      - name: AWS Cloudfront | Production
        if: github.ref == 'refs/heads/master'
        run: aws cloudfront create-invalidation --distribution-id E51L08TW3241I --paths "/*"
