name: Build

on:
  push: 
    branches: [staging, master]
  pull_request:
    branches: [staging, master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 8
      
      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache
      
      - name: Lint Check
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Help Codecov detect commit SHA
          fetch-depth: 2
      
      - uses: actions/setup-node@v2
        with:
          node-version: 8
      
      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache
      
      - name: Run Tests
        run: yarn test
      
      - name: Upload Codecov Reports
        uses: codecov/codecov-action@v2 
   
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 8
      
      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache
      
      - name: Build App
        run: yarn run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}
      
      # Deploying to S3 with the --delete flag can be problematic if there's nothing already in the bucket
      # Solution: deploy once without the flag, then deploy a second time with the flag to delete previous files
      - name: Deploy to S3
        # if: github.ref == 'refs/heads/master'
        run: aws s3 sync dist ${{ secrets.AWS_WEB_STATIC_BUCKET_NAME }} --region us-east-1 --acl public-read --cache-control 'public, max-age=300'
      
      - name: AWS Cloudfront
        if: github.ref == 'refs/heads/master'
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
      
      - name: Deploy to S3 and Delete Previous Files
        if: github.ref == 'refs/heads/master'
        run: aws s3 sync dist  ${{ secrets.AWS_WEB_STATIC_BUCKET_NAME }} --region us-east-1 --acl public-read --cache-control 'public, max-age=300' --delete
